{
  "id": "topic_5417041",
  "title": "Napo_coin",
  "author": "Napo_coin",
  "created_time": "October 14, 2022, 01:53:49 AM",
  "content": "It's a feathercoin forkI compiled a linux qt wallet and when I run it, it give outterminate called after throwing an instance of 'std::out_of_range' what(): basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 13) Aborted (core dumped)any idea what did it mean?",
  "score": 0,
  "upvotes": 0,
  "downvotes": 0,
  "url": "https://bitcointalk.org/index.php?topic=5417041",
  "comments": [
    {
      "author": "owlcatz",
      "created_time": "October 14, 2022, 03:51:39 PM",
      "body": "Google says:https://stackoverflow.com/questions/70125011/error-terminate-called-after-throwing-an-instance-of-stdout-of-rangeCan you put in a bug report on their github or contact a dev of the wallet software you are using? ü§∑‚Äç‚ôÇÔ∏è",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "vv181",
      "created_time": "October 14, 2022, 04:49:22 PM",
      "body": "At least put the code where it related to the error or just simply put the repository link that you currently use, so others may be able to debug it further.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "Napo_coin",
      "created_time": "October 15, 2022, 02:59:03 AM",
      "body": "https://github.com/Zetalon0/Napocoin/tree/Napocoin-2.0",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "owlcatz",
      "created_time": "October 15, 2022, 03:24:34 AM",
      "body": "Quote from: Napo_coin on October 15, 2022, 02:59:03 AMhttps://github.com/Zetalon0/Napocoin/tree/Napocoin-2.0Right. so put in your issue here with all the code and error etc... https://github.com/Zetalon0/Napocoin/issues",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "vv181",
      "created_time": "October 15, 2022, 05:31:41 PM",
      "body": "As the referred link above, the error looks like indicates that some particular code index is out of bounds. I think it is expected since you modified the code into your own fork, the problem is I did not understand the codebase well enough but judging by the time of the error, maybe it has something to do with the wallet codebase. Something must be modified in your end but the other related configurations haven't been updated.Quote from: owlcatz on October 15, 2022, 03:24:34 AMRight. so put in your issue here with all the code and error etc... https://github.com/Zetalon0/Napocoin/issuesWell, seems it would do nothing since OP is the sole developer.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "Napo_coin",
      "created_time": "October 17, 2022, 05:47:16 AM",
      "body": "Quote from: vv181 on October 15, 2022, 05:31:41 PMAs the referred link above, the error looks like indicates that some particular code index is out of bounds. I think it is expected since you modified the code into your own fork, the problem is I did not understand the codebase well enough but judging by the time of the error, maybe it has something to do with the wallet codebase. Something must be modified in your end but the other related configurations haven't been updated.Quote from: owlcatz on October 15, 2022, 03:24:34 AMRight. so put in your issue here with all the code and error etc... https://github.com/Zetalon0/Napocoin/issuesWell, seems it would do nothing since OP is the sole developer.I agree, i am looking at qt and gui code atm, as the daemon works fine, only qt wallet give out the error",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    }
  ]
}